[package]
name = "rustyrts"
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private=true

[[bin]]
name = "cargo-rustyrts"

[[bin]]
name = "rustyrts-static"

[[bin]]
name = "rustyrts-dynamic"

[dependencies]
log = "0.4"
serde_json = "1.0.61"
queues = "1.0.2"
itertools = "0.10.5"
test-log = "0.2.11"
env_logger = "0.10.0"
regex = "1.7.1"
lazy_static = "1.4.0"
once_cell = "1.17.1"