[package]
name = "threading"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test1_panic = []
test2_panic = []
changes_test1 = []
changes_test2 = []

[dependencies]
threadpool = "1.8.1"
