[package]
name = "drop"
version = "0.1.0"
edition = "2021"

[features]
changes_drop = []
drop_inner = []
drop_outer = []
drop_direct = []
drop_delegate = []
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
