[package]
name = "rustyrts-static-sysroot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
rustc-build-sysroot = "0.4.2"
rustc_version = "0.4.0"
