name: rustyrts - Test

on:
  push:
    branches: [ main, develop ]
    tags:
      - "v*.*.*"
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2023-12-28
        override: true

    - name: Install Rust components
      run: rustup component add rustc-dev llvm-tools-preview

    - name: Check Rust version
      run: cargo --version && rustc --version

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.0
           
    - name: Build
      run: cargo build --verbose --locked
    
    - name: Run tests
      run: cargo test --verbose --locked
